#[derive(Copy, Clone, Debug, PartialEq)]
pub enum Meter {}
#[derive(Copy, Clone, Debug, PartialEq)]
pub enum Kilogram {}
#[derive(Copy, Clone, Debug, PartialEq)]
pub enum Second {}
#[derive(Copy, Clone, Debug, PartialEq)]
pub enum Ampere {}
#[derive(Copy, Clone, Debug, PartialEq)]
pub enum Kelvin {}
#[derive(Copy, Clone, Debug, PartialEq)]
pub enum Mole {}
#[derive(Copy, Clone, Debug, PartialEq)]
pub enum Candela {}
