[package]
name = "aether-fft"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license-file.workspace = true

[features]
default = ["no_std"]
std = ["aether-core/std"]
no_std = ["aether-core/no_std"]

[lib]
crate-type = ["rlib"]

[dependencies]
aether-core = { path = "../aether-core", default-features = false }