[package]
name = "aether"
edition.workspace = true
version.workspace = true
license-file.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
aether-core = { path = "../aether-core" }
aether-fft = { path = "../aether-fft" }
aether-catalogs = { path = "../aether-catalogs" }
aether-benchmark = { path = "../aether-benchmark" }
aether-examples = { path = "../aether-examples" }
aether-fluids = { path = "../aether-fluids" }
aether-graphics = { path = "../aether-graphics" }
aether-ml = { path = "../aether-ml" }
aether-models = { path = "../aether-models" }
aether-opt = { path = "../aether-opt" }
aether-rand = { path = "../aether-rand" }
aether-shapes = { path = "../aether-shapes" }
aether-stats = { path = "../aether-stats" }

[features]
default = []
# Pass-through commonly used features to the subcrates
serde = ["aether-core/serde"]
bincode = ["aether-core/bincode"]
std = [
    "aether-core/std",
    "aether-fft/std",
    "aether-catalogs/std",
    "aether-benchmark/std",
    "aether-fluids/std",
    "aether-graphics/std",
    "aether-ml/std",
    "aether-models/std",
    "aether-opt/std",
    "aether-rand/std",
    "aether-shapes/std",
    "aether-stats/std",
]
no_std = [
    "aether-core/no_std",
    "aether-fft/no_std",
    "aether-benchmark/no_std",
    "aether-fluids/no_std",
    "aether-graphics/no_std",
    "aether-ml/no_std",
    "aether-models/no_std",
    "aether-opt/no_std",
    "aether-rand/no_std",
    "aether-shapes/no_std",
    "aether-stats/no_std",
]
regex = ["aether-core/regex"]
rustyline = ["aether-core/rustyline"]
serde-json-core = ["aether-core/serde-json-core"]
simd = ["aether-core/simd"]
fma = ["aether-core/fma"]

[dev-dependencies]
# criterion = { workspace = true }

# [[bench]]
# name = "throughput"
# harness = false

# [[bench]]
# name = "precision"
# harness = false
